#!name=YouTube Ad Blocker (Apple TV)
#!desc=Blocks YouTube ads on Apple TV

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com),(PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com),(PROTOCOL,UDP)),REJECT
DOMAIN,pagead2.googlesyndication.com,REJECT
DOMAIN,googleads.g.doubleclick.net,REJECT
DOMAIN,adclick.g.doubleclick.net,REJECT
DOMAIN,www.googleadservices.com,REJECT
DOMAIN,www.googletagservices.com,REJECT
DOMAIN,ads.google.com,REJECT
DOMAIN,mobileads.google.com,REJECT

[URL Rewrite]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad - reject-200

ctier=[A-Z] ctier=A 302
^https?:\/\/s\.youtube\.com\/api\/stats\/ads - reject
^https?:\/\/www\.youtube\.com\/api\/stats\/ads - reject
^https?:\/\/www\.youtube\.com\/api\/stats\/qoe\?.*adcontext - reject
^https?:\/\/www\.youtube\.com\/pagead - reject
^https?:\/\/www\.youtube\.com\/ptracking - reject

[Script]
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch)\?,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Little34306/little34306.github.io/refs/heads/main/yt-adb.js,timeout=30

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com, s.youtube.com, www.youtube.com
